//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Application.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblVersion
    {
        public int id { get; set; }
        public string versionExe { get; set; }
        public string versionDatabase { get; set; }
        public string versionWeb { get; set; }
    }
}
